config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'
  get 'static_pages/home'
  get '/about', to: 'static_pages#about' #「/about」というアドレスにアクセスしてきたら、「static_pagesのabout」を呼び出す
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    default_scope -> { order('created_at DESC') }
    validates :user_id, presence: true
    validates :content, presence: true, length: { maximum: 240 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, foreign_key: "follower_id",
                                  class_name: "Relationship",
                                  dependent: :destroy
  has_many :followed_users, through: :active_relationships, source: :followed
  has_many :passive_relationships, foreign_key: "followed_id",
                                   class_name: "Relationship",
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower                                 
  
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }



  def feed
    Micropost.where("user_id = ?", id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def follow(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
    include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
     #「ApplicationController」というクラスを継承して、新たに「MicropostsController」というクラスを作っている
     before_action :only_loggedin_users, only: [:create, :destroy]

def create
     @micropost = current_user.microposts.build(micropost_params)
     if @micropost.save
          flash[:success] = "Successfully saved!"
          redirect_to root_url
     else
          @feed_items = []
          flash[:danger] = "Invalide content. Try again."
          redirect_to root_url
     end

end

def destroy
     Micropost.find(params[:id]).destroy
     redirect_to root_url
end

private
def micropost_params
     params.require(:micropost).permit(:content)
end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :only_loggedin_users
    def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
        respond_to do |format|
            format.html { redirect_to @user}
            format.js
        end
    end

    def destroy
        @user = Relationship.find(params[:id]).followed
        current_user.unfollow(@user)
        respond_to do |format|
            format.html { redirect_to @user}
            format.js
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   #「ApplicationController」というクラスを継承して、新たに「SessionsController」というクラスを作っている
   
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:session] = "Logged in success!"
      log_in user
      redirect_to user
    else
      render "new"
      flash.now[:danger] = "Login faled"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   if logged_in?
    @micropost = current_user.microposts.build 
    @user = current_user
    @feed_items = current_user.feed.paginate(page: params[:page], per_page:12)
   end
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #「ApplicationController」というクラスを継承して、新たに「UsersController」というクラスを作っている

  before_action :only_loggedin_users, only: [:index, :edit, :update, :destroy, :following, :follower]
  #editとupdateが実行される前にのみ、ログインしていない時にはlogin_urlを表示させる
  #before_actionとは、Controllerの全てのアクションが実行される前に何らかの処理を行う時に使用するもの
  before_action :correct_user, only: [:edit, :update]
  def new
    @user = User.new
  end

  def index #「http://localhost:3002/users/index」にアクセスするとindexのアクションメソッドが実行される
    @users = User.all #コントローラファイルにユーザーのデータを全て引っ張ってくる
    @users = User.paginate(page: params[:page], per_page: 10 )
  end
  

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Saved Successfully"
      redirect_to login_url
    else
      flash[:danger] = "Signup failed"
      render 'new' #newアクションに従って表示させる
    end
  end

  def show #Userクラスを用いて、idのユーザー情報を引っ張ってくる
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page:params[:page], per_page:12)
  end

  
  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to user_url
  end
 
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:session] = "Saved Successfully"
      redirect_to @user
    else
      flash[:danger] = "Invalid content. Try Again."
      render 'edit'
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page], per_page: 5)
    @all_users = @user.followed_users
    render 'show_follow'
  end

  def follower
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 5)
    @all_users = @user.followers
    render 'show_follow'
  end

private #クラスの外からは呼び出せない。同じインスタンス内でのみ、関数形式で呼び出せる。

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def only_loggedin_users
        redirect_to login_url unless logged_in? #ログインしていない時にはlogin_urlを表示させる
    end

    def log_in(user)
        session[:user_id] = user.id
    end

    
    def logged_in?
        !current_user.nil?
    end


    def current_user?(user)
        user == current_user
    end
      

    def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
      
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <%= link_to "AwesomeBlog", "#", class:"navbar-brand brand", id: "logo" %>
   <div class="collapse navbar-collapse">
       <ul class="navbar-nav mr-auto">
           <li class="nav-item">
               <%= link_to "Home", root_path, class: "nav-link" %>
           </li>
           <li class="nav-item">
               <%= link_to "About", about_path, class: "nav-link" %>
           </li>
           <li class="nav-item">
               <%= link_to "Contact us", contact_path, class: "nav-link" %>
           </li>
       </ul>
       <div class="form-inline my-2 my-lg-0">
       <ul class="navbar-nav mr-5">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if logged_in? %> <%= current_user.name%> <% else %> Account <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
               <% if logged_in? %>
                <%= link_to "Users List", users_path, class: "dropdown-item" %>
                <%= link_to current_user.name , current_user, class: "dropdown-item" %>
                <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
                <%= link_to "Logout", logout_path, class: "dropdown-item", method: "delete" %>
              <% else %>
                <%= link_to "Sign Up", signup_path, class: "dropdown-item" %>
                <%= link_to "Login", login_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
        </ul>
        </div>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Awesome Blog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>


  <body>
  <%= render 'layouts/header' %>

  <div class="container pt-2">
    <%= render "shared/error_messages" %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<div class="container">
<li>
    <h4><%= micropost.content %></h4>
    <span class="timestamp">
     Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
    <% if current_user?(micropost.user) %>
        <%= link_to raw("<i class='fa fa-trash text-danger'></i>"), micropost, method: :delete,
                                            data: { confirm: "Are you sure?"},
                                            title: micropost.content %>
        
    <% end %>                                        
</li>
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_error_messages.html.erb
<% flash.each do |type, msg| %>
    <% if type == "danger" %>
        <div class="alert alert-danger alert-dismissible fade show mt-4" role="alert">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% else %>
        <div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts-lists">
        <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>        

app/views/shared/_feed_item.html.erb
<li class="col12 my-4">
     <%= link_to gravatar_for(feed_item.user), feed_item.user%>
     <span class="user">
        <%= link_to feed_item.user.name, feed_item.user %>
     </span>
     <h4><%= feed_item.content %></h4>
     <span class="timestamp">
        Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
     </span>
      <% if current_user?(feed_item.user) %>
        <%= link_to raw("<i class='fa fa-trash text-danger'></i>"), feed_item, method: :delete,
                                            data: { confirm: "Are you sure?"},
                                            title: feed_item.content %>
    <% end %>  
</li>

app/views/shared/_micropost_form.html.erb
<div class="container">
    <%= form_for(@micropost) do |f| %>
        <div class="field">
            <%= f.text_area :content,
            placeholder: "Compose a new micropost...", class: "w-100" %>
        </div>
        <div class="text-center">
            <%= link_to raw("<i class='fas fa-pastafarianism text-danger'></i>"), class: "btn btn-block btn-primary" %> 
            <strong class="text-info">{Post!!</strong>
        </div>
    <% end %>  
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
    <div class= "stats">
        <a href = "<%= following_user_path(@user) %>">
            <strong id="following" class="stat">
            <%= @user.followed_users.count %>
            </strong>
            following
        </a>
        <a href="<%= followers_user_path(@user) %>">
            <strong id="followers" class="stat">
            <%= @user.followers.count %>
            </strong>
            followers
        </a>
    </div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(@user, size: 52), @user%>
<h1>
    <%= @user.name%>
</h1>
<span>
    <%= pluralize(@user.microposts.count, "micropost") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, "About me") %>
<div class="jumbotron mt-4 alert alert-light offset-md-2 col-md-8 offset-md-2">

<h1 class="text-center mt-4">About Me</h1>
<div class="row justify-content-around mt-4">
  <div class="card border-danger mb-3 col-4" style="max-width: 20rem;">
    <div class="card-header"><strong>Profile</strong></div>
    <div class="card-body text-danger">
      <h5 class="card-title">SHIZUE</h5>
      <p class="card-text">Birthday: July 17th</p>
      <p>Blood Type: O</p>
      <p>Favorit: Sailor Moon</p>
      <p>Dream: Annual income 100 million yen</p>
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs--gQ7LIo6nEQ6KDuuVbAP8iCi4XpeyAWaQ&usqp=CAU" 
           width="200" height="150">
    </div>
  </div>

  <div class="card" style="width: 18rem; col-4">
    <img src="https://img.fril.jp/img/317687134/l/895369537.jpg?1587374728">
      <div class="card-body">
        <p class="card-text">This is one of my friend named GOMA. 
        I met her at Osaka 2 years ago and bought without thinking. Whenever I see her face, I feel relax.</p>
      </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact Us") %>
<div class="jumbotron mt-4 alert alert-info offset-md-2 col-md-8 offset-md-2">
  <h1 class="text-center">Let's communicat!!</h1>
    <p class="text-center">If you are interested in my faverits, please contact me!!</p>

  <form>
    <div class="form-group">
      <label for="exampleFormControlInput1">Email address</label>
      <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Comment</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
  </form>
  <img class="d-block mx-auto" src="https://www.fashion-press.net/img/news/21449/sailormoon_add_4.jpg" width="500" height="300">
</div>
  

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if logged_in? %>
  <div class="row d-flex justify-content-center mt-4">
    <aside class="span col-3">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside> 
    <div class="col-6">
      <h3>Micropost</h3>
      <%= render 'shared/feed' %> 
    </div>     
<% else %>  
  <div class="jumbotron mt-4 alert alert-warning offset-md-2 col-md-8 offset-md-2">
    <h1 class="text-center"><strong>SHIZUE's ROOM</strong></h1>
    <p class="text-center">Welcome to my room!</p>
    <div class="row">
    <img class="col-4"
         src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAFg-daFel57Ape9ZNEWZ_GMhkpdep0xrk0A&usqp=CAU"
         width="200" height="300">
    <img class="d-block mx-auto col-4" 
         src="https://i.pinimg.com/236x/18/b4/48/18b4488baf802be319f4ffb1c429a6a3--sailor-moon-manga-naoko-takeuchi.jpg" 
         width="200" height="300">
    <img class="col-4"
         src="https://i.pinimg.com/originals/24/e6/1a/24e61a944f590eadcc727f600da40156.jpg"
         width="200" height="300">
  </div>
  <div class="text-center mt-3">
    <h1>Let's OTAKU activity!!</h1>
  </div>
<% end %>                 

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
    <div> <%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
       <%= form_for(@user) do |f| %>
           <%= f.label :name %>
           <%= f.text_field :name, class: "form-control" %>

           <%= f.label :email %>
           <%= f.text_field :email, class: "form-control" %>

           <%= f.label :password %>
           <%= f.password_field :password, class: "form-control" %>

           <%= f.label :password_confirmation, "Confirmation" %>
           <%= f.password_field :password_confirmation, class: "form-control" %>

           <%= f.submit class: "btn btn-block btn-primary" %>
       <% end %>
   </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), 
            html: { method: :delete },
            remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large btn-danger" %>
<% end %>

app/views/users/_user.html.erb
<li class="col-12 my-4">
    <%= link_to gravatar_for(user), user %>
    <span class="user">
        <%= link_to user.name, user %>
    </span>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Settings') %>
<div class="form">
   <h1 class="text-center">Settings</h1>
   <%= render 'form' %>           
</div>

app/views/users/index.html.erb
<% provide(:title, 'List of Users') %>
<div class="container">
  <div class="row d-flex justify-content-center">
    <%= will_paginate %>
  </div>
      <div class="row d-flex justify-content-center">
        <ul class="users">
            <% @users.each do |user| %>
                <li class="my-3">
                    <%= gravatar_for user, size: 52 %>
                    <%= link_to user.name, user %>
                    <%= link_to raw("<i class='fa fa-trash text-danger'></i>"), user_path(user), class: "text-danger", method: :delete, data: { confirm: "You sure?" } unless !current_user?(user)%>
                </li>
            <% end %>  
        </ul>  
      </div>
   <div class="row d-flex justify-content-center">
    <%= will_paginate %>
   </div>
</div>           

app/views/users/login.html.erb
<% provide(:title, 'Login') %>

<div class="form content">
   <h1 class="text-center">Login</h1>
   <div class="container">
       <%= form_for(:session, url: sessions_path) do |f| %>
           <%= f.label :email %>
           <%= f.text_field :email, class: "form-control" %>

           <%= f.label :password %>
           <%= f.password_field :password, class: "form-control" %>

           <%= f.submit "Login", class: "btn btn-block btn-primary" %>
       <% end %>
       <p>New here? <%= link_to "Sign up now!", signup_path %></p>
   </div>  
</div>
     

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="form">
   <h1 class="text-center">Sign up</h1>
   <%= render 'form' %>           
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row d-flex justify-content-center mt-4">
  <aside class="span col-3">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
          <%= render 'shared/stats' %>
    </section>
    <div>
      <img src="https://i.pinimg.com/236x/0a/e5/38/0ae53826e9bfa365e3eea16980bb92ea--sailor-moon-manga-sailor-moon-art.jpg" 
           alt="..." class="img-thumbnail mt-5">
    </div>
  </aside>

  <div class="col-6">
      <%= render 'follow_form' if logged_in? %>
      <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol>
           <%= render @microposts %>
        </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
        <%= gravatar_for @user %>
        <h1> <%= @user.name %> </h1>
        <span> <%= link_to "view my profile", @user %> </span>
        <span><b>Microposts</b> <%= @user.microposts.count %> </span>
    </section>
    <section class="stats">
          <%= render 'shared/stats' %>
          <% if @all_users.any? %>
            <div class="user_avatars">
                <% @all_users.each do |user| %>
                    <%= link_to gravatar_for(user, size: 30), user %>
                <% end %>
            </div>
          <% end %>
    </section>
  </aside>

  <div class="col-md-8">
      <h3> <%= @title %> </h3>
        <% if @users.any? %>
            <% @users.each do |user| %>
                <ul class="users follow">
                    <%= render user %>
                </ul>
            <% end %>
            <%= will_paginate %>
        <% end %>
  </div>
</div>